name: Execute Application Pipeline

   on:
     push:
       branches: [ "main" ]

   jobs:
     call-devops-template:
       uses: julio2019vp/mi-infra-templates/.github/workflows/ci-cd-template.yml@main

       with:
         IMAGE_NAME: "mi-aplicacion-net"
         IMAGE_TAG: "latest"
         DOCKERFILE_PATH: "Dockerfile"
         ACR_REGISTRY: "registryjvp.azurecr.io"
      
       secrets:
         AZURE_REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
         AZURE_REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
